name: MacOS Build (ARM64)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

  workflow_call:
      inputs:
        buildFlags:
          required: false
          type: string

jobs:
  build:
    name: MacOS Build (ARM64)
    permissions: write-all
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Restore action cache
        id: cache-build-macosarm-restore
        uses: actions/cache/restore@main
        with:
          key: cache-build-macosarm
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/

      - name: Install libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxpkg
          haxelib run hxpkg install --force

      - name: Downgrade Lime to 8.1.3
        run: |
          haxelib remove lime
          haxelib install lime 8.1.3

      - name: Compile
        run: haxelib run lime build macos -64 -D HXCPP_M64

      - name: Tar files
        run: tar -zcvf AlterEngine.tar.gz -C export/release/macos/bin .

      - name: Uploading artifact
        uses: actions/upload-artifact@main
        with:
          name: Alter Engine
          path: AlterEngine.tar.gz
          if-no-files-found: error

      - name: Clearing already existing cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-build-macosarm") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Cache cleared.")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Uploading new cache
        id: cache-build-macosarm-save
        uses: actions/cache/save@main
        with:
          key: cache-build-macosarm
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/